name: Space_V4_Final_Fix
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Theos
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git lua5.3 liblua5.3-dev
          git clone --recursive https://github.com/theos/theos.git ~/theos

      - name: Clonar SDK (Bypass 295k)
        run: |
          # Em vez de curl/tar, usamos o Git Clone que o GitHub não bloqueia
          mkdir -p ~/theos/sdks
          git clone --depth 1 https://github.com/theos/sdks.git ~/temp_sdks
          cp -r ~/temp_sdks/iPhoneOS14.5.sdk ~/theos/sdks/
          rm -rf ~/temp_sdks

      - name: Build Space Xit V4
        run: |
          export THEOS=~/theos
          export PATH=$THEOS/bin:$PATH
          # Limpeza de caracteres do Windows (Anti-Erro 25)
          find . -type f -exec sed -i 's/\r$//' {} +
          make clean package FINALPACKAGE=1

      - name: Upload da V4
        uses: actions/upload-artifact@v4
        with:
          name: SpaceXit_V4_Final
          path: packages/*.deb
